//! Declarative macros for shrinking chain plugin boilerplate.
//!
//! Today's [`ChainPlugin`] trait has eleven accessor methods that every
//! chain crate implements identically — return a stored field, no
//! computation. [`chain_plugin_accessors!`] generates ten of those
//! eleven methods inside an existing `impl ChainPlugin for X` block
//! from a single declarative wiring map of *field names*, leaving the
//! chain-specific async methods (`check_rpc_health`, `send_transfer`,
//! `estimate_fee_display`, `fetch_history`, `fetch_token_balance`) and
//! the `tx_builder_any` accessor (which varies per chain) to be written
//! normally.
//!
//! The macro takes field names — not full expressions — because Rust's
//! macro hygiene rules forbid a `macro_rules!` expansion from binding
//! to a `self` parameter introduced by an enclosing function. Passing
//! `&self.field` would parse as call-site tokens at the impl-block
//! level where `self` is not yet in scope. By taking idents instead,
//! the macro emits `&self.<field>` from inside its own expansion where
//! the `self` it produces matches the `&self` parameter on each method
//! it emits.
//!
//! [`ChainPlugin`]: dontyeet_primitives::traits::ChainPlugin

/// Emit ten of the eleven mechanical accessor methods of [`ChainPlugin`]
/// inside an existing `impl ChainPlugin for X` block.
///
/// Every chain plugin returns stored fields from these methods with no
/// computation — this macro removes that ~30 lines of per-chain
/// boilerplate so chain authors only write the chain-specific async
/// methods (`check_rpc_health`, `send_transfer`, etc.) and the
/// `tx_builder_any` accessor (which varies between chains).
///
/// Each argument names a struct field on the implementing type. The
/// macro emits `&self.<field>` (or `&self.<config_field>.chain_id` for
/// the metadata accessors). `network` is a single argument because both
/// `network_provider()` and `rpc_endpoints()` always return the same
/// stored value (typically a `NetworkCatalog`).
///
/// `tx_builder_any` is intentionally not generated by this macro — it
/// is the only accessor where chains genuinely differ (most chains
/// return `self` as a placeholder; EVM returns `&self.tx_builder`).
/// Write it inline next to the chain-specific async methods.
///
/// All trait paths emitted by the macro are fully qualified
/// (`::dontyeet_primitives::...`), so the call site does not need to
/// import the nine trait types it would otherwise reference.
/// `dontyeet_primitives` must be a dependency of the calling crate
/// (it already is for every chain crate today).
///
/// # Examples
///
/// ```ignore
/// use std::any::Any;
///
/// #[async_trait]
/// impl ChainPlugin for BtcChainPlugin {
///     dontyeet_chain::chain_plugin_accessors! {
///         config_field    = config,
///         key_deriver     = key_deriver,
///         address_encoder = address_encoder,
///         balance_fetcher = balance_fetcher,
///         fee_estimator   = fee_estimator,
///         signer          = tx_signer,
///         broadcaster     = broadcaster,
///         network         = network_catalog,
///     }
///
///     fn tx_builder_any(&self) -> &dyn Any {
///         // Bitcoin tx building is complex (UTXO); placeholder = self.
///         self
///     }
///
///     async fn check_rpc_health(&self, network: &NetworkId) -> Result<RpcHealthResult> {
///         // chain-specific behavior
///     }
///     // ... other async methods
/// }
/// ```
#[macro_export]
macro_rules! chain_plugin_accessors {
    (
        config_field    = $config_field:ident,
        key_deriver     = $key_deriver:ident,
        address_encoder = $address_encoder:ident,
        balance_fetcher = $balance_fetcher:ident,
        fee_estimator   = $fee_estimator:ident,
        signer          = $signer:ident,
        broadcaster     = $broadcaster:ident,
        network         = $network:ident $(,)?
    ) => {
        fn chain_id(&self) -> &::dontyeet_primitives::chain::ChainId {
            &self.$config_field.chain_id
        }
        fn native_asset(&self) -> &::dontyeet_primitives::asset::AssetInfo {
            &self.$config_field.native_asset
        }
        fn key_deriver(&self) -> &dyn ::dontyeet_primitives::traits::KeyDeriver {
            &self.$key_deriver
        }
        fn network_provider(&self) -> &dyn ::dontyeet_primitives::traits::NetworkProvider {
            &self.$network
        }
        fn rpc_endpoints(&self) -> &dyn ::dontyeet_primitives::traits::RpcEndpointProvider {
            &self.$network
        }
        fn address_encoder(&self) -> &dyn ::dontyeet_primitives::traits::AddressEncoder {
            &self.$address_encoder
        }
        fn balance_fetcher(&self) -> &dyn ::dontyeet_primitives::traits::BalanceFetcher {
            &self.$balance_fetcher
        }
        fn fee_estimator_any(&self) -> &dyn ::core::any::Any {
            &self.$fee_estimator
        }
        fn signer(&self) -> &dyn ::dontyeet_primitives::traits::TransactionSigner {
            &self.$signer
        }
        fn broadcaster(&self) -> &dyn ::dontyeet_primitives::traits::TransactionBroadcaster {
            &self.$broadcaster
        }
    };
}

// Rust guideline compliant 2026-05-02
