// BNB Smart Chain Contract Addresses
// Auto-generated by deploy workflow

pub const YEET_TOKEN_ADDRESS: &str   = "0x0f1963829c6cc7A925E2F46949C3b248D69297c7";
pub const YEET_TIPPING_ADDRESS: &str = "0xDbB4a813C1e39914bAbD473D0BDe559F69B30b97";
pub const YEET_NFT_ADDRESS: &str     = "0x8F518F1BCdcaAA0cb5b1690ebdC72152b6060F51";
pub const BSC_TESTNET_CHAIN_ID: u64  = 97;
pub const BSC_MAINNET_CHAIN_ID: u64  = 56;
pub const BSC_TESTNET_RPC: &str      = "https://bsc-testnet-dataseed.bnbchain.org";
pub const BSC_MAINNET_RPC: &str      = "https://bsc-dataseed.bnbchain.org";
pub const BSC_TESTNET_EXPLORER: &str = "https://testnet.bscscan.com";
pub const BSC_MAINNET_EXPLORER: &str = "https://bscscan.com";
